version : '3.7'

services:
  laravel:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        UID: ${UID}
        UNAME: dazl
    container_name: "dazl-backend"
    command: [ "php", "artisan", "serve", "--host", "0.0.0.0", "--port", "5000" ]
    volumes :
      - "./:/app"
      - "/app/vendor"
    depends_on:
      - "dazl-mysql"
      - "dazl-mysql-testing"
    ports:
      - 5000:5000

  dazl-mysql:
    image: mysql:8
    container_name: dazl-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password

  dazl-mysql-testing:
    image: mysql:8
    container_name: dazl-mysql-testing
    volumes:
      - mysql_testing_data:/etc/mysql
    restart: always
    tmpfs: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

volumes:
  mysql_data:
  mysql_testing_data:
