<?php

namespace Tests;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Faker;
abstract class TestCase extends BaseTestCase
{
    use CreatesApplication ,DatabaseTransactions;
    protected $faker ;
    public function setUp(): void
    {
        $this->faker = Faker\Factory::create();

        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
